POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "stayhungry"
}

###

POST http://localhost:3001/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGYzMzE5YTUzNzc2ZTRjZjE2YmM5OSIsImlhdCI6MTY0MjAzODQ5NSwiZXhwIjoxNjQyNjQzMjk1fQ.F6QG3aN-ZGGjZ15ywkcxAemf_8eZsOQonGWud22ZRmk

{
    "oldPassword": "stayhungry",
    "newPassword": "iloveyou"
}

